openapi: 3.0.3
info:
  title: 論文系統架構說明（右上角「選擇系統」查看各系統API）
  description: |

    
    # 論文系統整體架構

    本系統包含兩大主要系統，分別服務不同的使用者群體和功能需求：

    ## 🎓 博碩士論文系統 (NDLTD)
    
    **服務對象：** 博士、碩士研究生及一般讀者
    
    **系統特色：**
    - 國家級論文典藏與檢索平台
    - 與國家圖書館整合
    - 提供完整的論文生命週期管理
    - 支援對外 API 介接服務

    ### 📚 博碩士論文系統 讀者端
    - **功能：** 論文檢索、瀏覽、下載
    - **特色：** 
      - 支援多種檢索方式（關鍵字、進階搜尋）
      - 個人收藏管理
      - 檢索歷史記錄
      - LLM 語義檢索（AI 智能推薦）
      - 統計資訊查詢
    - **使用者：** 一般讀者、研究人員、學生

    ### 🏛️ 博碩士論文系統 國圖端
    - **功能：** 論文審查、管理、統計
    - **特色：**
      - 論文審查流程管理
      - 退件處理與追蹤
      - 系統統計與報表
      - 使用者權限管理
    - **使用者：** 國家圖書館管理員、審查人員

    ### 🔌 博碩士論文系統 對外API介接服務
    - **功能：** 提供標準化 API 介面
    - **特色：**
      - RESTful API 設計
      - 支援第三方系統整合
      - 資料標準化輸出
      - 安全認證機制
    - **使用者：** 外部系統開發者、合作機構

    ---

    ## 🏫 大學論文系統 (NDLTDSCH)
    
    **服務對象：** 各大學院校及其師生
    
    **系統特色：**
    - 校園級論文管理平台
    - 支援多校部署
    - 客製化校園需求
    - 與博碩士論文系統介接

    ### 🚪 大學論文系統 入口頁
    - **功能：** 系統入口與導航
    - **特色：**
      - 統一身份認證
      - 角色權限分流
      - 系統公告管理
      - 使用說明與幫助
    - **使用者：** 所有系統使用者

    ### 🏛️ 大學論文系統 學校端
    - **功能：** 學校管理功能
    - **特色：**
      - 學生論文審核
      - 指導教授管理
      - 系所權限設定
      - 畢業審查流程
    - **使用者：** 學校管理員、系所承辦人員

    ### 👨‍🎓 大學論文系統 學生端
    - **功能：** 學生論文上傳與管理
    - **特色：**
      - 論文檔案上傳
      - 論文資料填寫
      - 授權設定管理
      - 審查狀態追蹤
      - 退件處理申請
    - **使用者：** 在學學生、畢業生

    ### 🔍 大學論文系統 檢索端
    - **功能：** 校園論文檢索
    - **特色：**
      - 校內論文搜尋
      - 權限控制檢索
      - 統計分析功能
      - 與國家系統介接
    - **使用者：** 校內師生、研究人員


    ## 📋 技術特色

    - **統一 API 格式：** 採用 Cloudflare API 標準格式
    - **安全認證：** JWT Bearer Token 認證機制
    - **多語言支援：** 中英文介面與內容
    - **響應式設計：** 支援各種裝置瀏覽
    - **高可用性：** 分散式架構設計
    - **標準化介接：** OpenAPI 3.0 規範

  version: 1.0.0
  contact:
    name: Github 原始碼
    url: https://github.com/chouhsiang/thesis-swagger
