# swagger.yaml

openapi: 3.0.3
info:
  title: Taiwan Thesis Pulse 最新公告 API
  description: 提供最新公告列表與公告詳細內容
  version: 1.4.0
servers:
  - url: https://api.taiwan-thesis-pulse.lovable.app
paths:
  /api/announcements:
    get:
      summary: 取得最新公告列表
      description: 取得最新公告，顯示短內容 summary
      parameters:
        - name: page
          in: query
          description: 分頁頁碼（預設為 1）
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          description: 每頁筆數（預設為 10）
          required: false
          schema:
            type: integer
            default: 10
        - name: type
          in: query
          description: 公告分類（系統公告、最新消息）
          required: false
          schema:
            type: string
            enum: [系統公告, 最新消息]
        - name: tag
          in: query
          description: 公告標籤（重要、新功能），可多選（以逗號分隔）
          required: false
          schema:
            type: string
            example: "重要,新功能"
      responses:
        '200':
          description: 成功取得公告列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: 公告總數
                    example: 1
                  page:
                    type: integer
                    description: 當前頁碼
                    example: 1
                  pageSize:
                    type: integer
                    description: 每頁筆數
                    example: 10
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: 公告唯一識別碼
                          example: "20240115"
                        title:
                          type: string
                          description: 公告標題
                          example: "系統維護公告"
                        type:
                          type: string
                          description: 公告分類
                          example: "系統公告"
                        tags:
                          type: array
                          description: 公告標籤
                          items:
                            type: string
                          example: ["重要"]
                        summary:
                          type: string
                          description: 公告短內容
                          example: "2024/01/15 凌晨2:00-4:00系統維護，暫停服務"
                        date:
                          type: string
                          format: date
                          description: 公告日期
                          example: "2024-01-15"
        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤

  /api/announcements/{id}:
    get:
      summary: 取得公告詳細內容
      description: 依公告 id 取得完整公告內容，包含 summary 與 content
      parameters:
        - name: id
          in: path
          required: true
          description: 公告唯一識別碼
          schema:
            type: string
            example: "20240115"
      responses:
        '200':
          description: 成功取得公告詳細內容
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: 公告唯一識別碼
                    example: "20240115"
                  title:
                    type: string
                    description: 公告標題
                    example: "系統維護公告"
                  type:
                    type: string
                    description: 公告分類
                    example: "系統公告"
                  tags:
                    type: array
                    description: 公告標籤
                    items:
                      type: string
                    example: ["重要"]
                  summary:
                    type: string
                    description: 公告短內容
                    example: "2024/01/15 凌晨2:00-4:00系統維護，暫停服務"
                  content:
                    type: string
                    description: 公告完整內容
                    example: "2024/01/15 凌晨2:00-4:00進行系統維護，期間將暫停服務，請提前儲存資料。"
                  date:
                    type: string
                    format: date
                    description: 公告日期
                    example: "2024-01-15"
        '404':
          description: 找不到該公告
        '400':
          description: 錯誤的請求參數
        '500':
          description: 伺服器錯誤
components: {}
